sudo: false
language: python
python: 3.5

matrix:
    fast_finish: true
    include:
        - os: linux
          dist: trusty
          python: 2.7
        - os: linux
          dist: trusty
          python: 3.4
        - os: linux
          dist: trusty
          python: 3.5
        - os: linux
          dist: trusty
          python: 3.6

        - os: osx
          language: generic
          env: PYVERSION='2.7.13'
        - os: osx
          language: generic
          env: PYVERSION='3.4.0'
        - os: osx
          language: generic
          env: PYVERSION='3.5.0'
        - os: osx
          language: generic
          env: PYVERSION='3.6.0'

before_install:
    - echo "before_install"
    - export PATH="$HOME/miniconda3/bin:$PATH"
    - df -h
    - pwd
    - uname -a
    - git --version
    - git tag

install:
    - echo "install start"
    - chmod +x ci/travis_install.sh
    - ci/travis_install.sh
    - echo "install done"

# command to run tests
script:
    - source activate dbcollection
    - pytest --cov=dbcollection dbcollection/tests/

after_success:
    - echo "Upload code coverage to codecov"
    - ls -lha
    - bash <(curl -s https://codecov.io/bash)